language: rust
cache: cargo

matrix:
  allow-failures:
    -rust: nightly

env:
  - RUST_TEST_THREADS=1

before_script:
  - rustup install nightly
  - cargo +nightly install --force rustfmt-nightly

script: 
  - cargo +nightly fmt -- --check
  - cargo build --verbose
  - cargo test --verbose
